export const product =[
    { 
        id: "1ads421egjdsc",
        name: "nike", 
        description: "Get comfy and comfortable with the new 2019 designer sneaker for all your events", 
        image: "https://res.cloudinary.com/dbdrtuscd/image/upload/v1624535985/sneakers_xmukzp.png", 
        price: "45,000", 
        location: "Lagos", 
        stock: 5, 
    },
    { 
        id: "2ads421egjdsc",
        name: "selfie stick", 
        description: "Get easy to use designer selfie stick", 
        image: "https://res.cloudinary.com/dbdrtuscd/image/upload/v1624535985/hand_u51x9i.png", 
        price: "5,000", 
        location: "Abuja", 
        stock: 5, 
    },
    { 
        id: "3ads421egjdsc",
        name: "cocacola", 
        description: "Get your refreshing bottle of cocacola,quench your taste", 
        image: "https://res.cloudinary.com/dbdrtuscd/image/upload/v1624535985/cocacola_qvwok5.png", 
        price: "2,000", 
        location: "Kaduna", 
        stock: 5, 
    },
    { 
        id: "4ads421egjdsc",
        name: "air freshner", 
        description: "Get nice smelling air freshner for your homes and cars", 
        image: "https://res.cloudinary.com/dbdrtuscd/image/upload/v1624535986/box_h5pkv5.png", 
        price: "3,000", 
        location: "Rivers", 
        stock: 5, 
    },
    { 
        id: "5ads421egjdsc",
        name: "lunch bag", 
        description: "Get easy to use lunch bag to keep your food warm", 
        image: "https://res.cloudinary.com/dbdrtuscd/image/upload/v1624535986/food_bbrkht.png", 
        price: "45,000", 
        location: "Lagos", 
        stock: 5, 
    },
    { 
        id: "6ads421egjdsc",
        name: "seeds", 
        description: "Get beautiful, treated, hybrid flower seeds", 
        image: "https://res.cloudinary.com/dbdrtuscd/image/upload/v1624535986/bag_m8wz3k.png", 
        price: "45,000", 
        location: "Rivers", 
        stock: 5, 
    },
    { 
        id: "7ads421egjdsc",
        name: "umbrella", 
        description: "Get comfy and comfortable in rainy days with good umbrella", 
        image: "https://res.cloudinary.com/dbdrtuscd/image/upload/v1624535985/cocacola_qvwok5.png",
        price: "45,000", 
        location: "Kaduna", 
        stock: 5, 
    },
    { 
        id: "8ads421egjdsc",
        name: "nike", 
        description: "Get comfy and comfortable with the new 2019 designer sneaker for all your events", 
        image: "https://res.cloudinary.com/dbdrtuscd/image/upload/v1624535986/bag_m8wz3k.png", 
        price: "45,000", 
        location: "Abuja", 
        stock: 5, 
    },
    { 
        id: "9ads421egjdsc",
        name: "nike", 
        description: "Get comfy and comfortable with the new 2019 designer sneaker for all your events", 
        image: "https://res.cloudinary.com/dbdrtuscd/image/upload/v1624535986/bag_m8wz3k.png", 
        price: "45,000", 
        location: "Lagos", 
        stock: 5, 
    },
    { 
        id: "10ads421egjdsc",
        name: "nike", 
        description: "Get comfy and comfortable with the new 2019 designer sneaker for all your events", 
        image: "https://res.cloudinary.com/dbdrtuscd/image/upload/v1624535986/bag_m8wz3k.png", 
        price: "45,000", 
        location: "Abuja", 
        stock: 5, 
    },
    { 
        id: "11ads421egjdsc",
        name: "bag", 
        description: "Get comfy and comfortable with the new 2019 designer sneaker for all your events", 
        image: "https://res.cloudinary.com/dbdrtuscd/image/upload/v1624535985/cocacola_qvwok5.png", 
        price: "45,000", 
        location: "Kaduna", 
        stock: 5, 
    },
    { 
        id: "12ads421egjdsc",
        name: "nike", 
        description: "Get comfy and comfortable with the new 2019 designer sneaker for all your events", 
        image: "https://res.cloudinary.com/dbdrtuscd/image/upload/v1624535986/bag_m8wz3k.png", 
        price: "N45,000", 
        location: "Rivers", 
        stock: 5, 
    },
        
]