export const product =[
    { 
        id: "1ads421egjdsc",
        name: "NIKE Huararche 2019", 
        description: "Get comfy and comfortable with the new 2019 designer sneaker for all your events", 
        image: "https://res.cloudinary.com/dbdrtuscd/image/upload/v1624535985/sneakers_xmukzp.png", 
        price: "45,000 - 90,000", 
        location: "Lagos", 
        stock: 5, 
    },
    { 
        id: "2ads421egjdsc",
        name: "NIKE Huararche 2019", 
        description: "Get comfy and comfortable with the new 2019 designer sneaker for all your events", 
        image: "https://res.cloudinary.com/dbdrtuscd/image/upload/v1624535985/hand_u51x9i.png", 
        price: "45,000 - 90,000", 
        location: "Lagos", 
        stock: 5, 
    },
    { 
        id: "3ads421egjdsc",
        name: "NIKE Huararche 2019", 
        description: "Get comfy and comfortable with the new 2019 designer sneaker for all your events", 
        image: "https://res.cloudinary.com/dbdrtuscd/image/upload/v1624535985/cocacola_qvwok5.png", 
        price: "45,000 - 90,000", 
        location: "Lagos", 
        stock: 5, 
    },
    { 
        id: "4ads421egjdsc",
        name: "NIKE Huararche 2019", 
        description: "Get comfy and comfortable with the new 2019 designer sneaker for all your events", 
        image: "https://res.cloudinary.com/dbdrtuscd/image/upload/v1624535986/box_h5pkv5.png", 
        price: "45,000 - 90,000", 
        location: "Lagos", 
        stock: 5, 
    },
    { 
        id: "5ads421egjdsc",
        name: "NIKE Huararche 2019", 
        description: "Get comfy and comfortable with the new 2019 designer sneaker for all your events", 
        image: "https://res.cloudinary.com/dbdrtuscd/image/upload/v1624535986/food_bbrkht.png", 
        price: "45,000 - 90,000", 
        location: "Lagos", 
        stock: 5, 
    },
    { 
        id: "6ads421egjdsc",
        name: "NIKE Huararche 2019", 
        description: "Get comfy and comfortable with the new 2019 designer sneaker for all your events", 
        image: "https://res.cloudinary.com/dbdrtuscd/image/upload/v1624535986/bag_m8wz3k.png", 
        price: "45,000 - 90,000", 
        location: "Lagos", 
        stock: 5, 
    },
    { 
        id: "7ads421egjdsc",
        name: "NIKE Huararche 2019", 
        description: "Get comfy and comfortable with the new 2019 designer sneaker for all your events", 
        image: "https://res.cloudinary.com/dbdrtuscd/image/upload/v1624535986/bag_m8wz3k.png", 
        price: "45,000 - 90,000", 
        location: "Lagos", 
        stock: 5, 
    },
    { 
        id: "8ads421egjdsc",
        name: "NIKE Huararche 2019", 
        description: "Get comfy and comfortable with the new 2019 designer sneaker for all your events", 
        image: "https://res.cloudinary.com/dbdrtuscd/image/upload/v1624535986/bag_m8wz3k.png", 
        price: "45,000 - 90,000", 
        location: "Lagos", 
        stock: 5, 
    },
    { 
        id: "9ads421egjdsc",
        name: "NIKE Huararche 2019", 
        description: "Get comfy and comfortable with the new 2019 designer sneaker for all your events", 
        image: "https://res.cloudinary.com/dbdrtuscd/image/upload/v1624535986/bag_m8wz3k.png", 
        price: "45,000 - 90,000", 
        location: "Lagos", 
        stock: 5, 
    },
    { 
        id: "10ads421egjdsc",
        name: "NIKE Huararche 2019", 
        description: "Get comfy and comfortable with the new 2019 designer sneaker for all your events", 
        image: "https://res.cloudinary.com/dbdrtuscd/image/upload/v1624535986/bag_m8wz3k.png", 
        price: "45,000 - 90,000", 
        location: "Lagos", 
        stock: 5, 
    },
        
]